language: python

python: 2.7

os:
  - linux

sudo: required

matrix:
  include:
    - os: linux
      python: 3.4
      env: TOX_ENV=pylint
    - os: linux
      env: TOX_ENV=py27
    - os: linux
      env: TOX_ENV=py34
    - os: linux
      env: TOX_ENV=py35
      python: 3.5
    - os: linux
      env: TOX_ENV=py36
      python: 3.6
    - os: osx
      language: generic
      env:
        - TOX_ENV=py27
        - PYENV_VERSION="2.7.13"
    - os: osx
      language: generic
      env:
        - TOX_ENV=py34
        - PYENV_VERSION="3.4.6"
    - os: osx
      language: generic
      env:
        - TOX_ENV=py35
        - PYENV_VERSION="3.5.3"
    - os: osx
      language: generic
      env:
        - TOX_ENV=py36
        - PYENV_VERSION="3.6.0"
  exclude:
    - python: 2.7 # hack to exclude default no-env travis job

install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update
      brew upgrade pyenv
    fi

before_script:
  # Install custom pyton version on OSX
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      if [[ ! -z "$VIRTUAL_ENV" ]]; then deactivate; fi
      eval "$(pyenv init -)"
      pyenv install "$PYENV_VERSION"
      pyenv global "$PYENV_VERSION"
    fi
  - python -m pip install -U pip setuptools tox pytest

script:
  - tox -e $TOX_ENV
